#
# emCode
# ----------------------------------
# Embedded computing with make
#
# Copyright © Rei Vilo, 2010-2026
# All rights reserved
#
# Last update: 19 Sep 2026 release 14.8.16
#

ifeq ($(MAKEFILE_NAME),)

STM32DUINO_INITIAL = $(ARDUINO_PACKAGES_PATH)/STMicroelectronics

ifneq ($(wildcard $(STM32DUINO_INITIAL)/hardware/stm32),)
    STM32DUINO_APP = $(STM32DUINO_INITIAL)
    STM32DUINO_PATH = $(STM32DUINO_APP)
    STM32DUINO_BOARDS = $(STM32DUINO_APP)/hardware/stm32/$(STM32DUINO_RELEASE)/boards.txt
endif

BOARD_CHECK := 0
ifneq ($(filter STM32DUINO,$(GCC_PREPROCESSOR_DEFINITIONS)),)
ifneq ($(call PARSE_FILE,$(BOARD_TAG),name,$(STM32DUINO_BOARDS)),)
    BOARD_CHECK := 1
endif
endif

ifeq ($(BOARD_CHECK),1)
MAKEFILE_NAME = STM32duino
RELEASE_CORE = $(STM32DUINO_RELEASE)
READY_FOR_EMCODE_NEXT = 1

# Complicated menu system for Arduino 1.5
# Another example of Arduino's quick and dirty job
#
BOARD_TAGS_LIST = $(BOARD_TAG) $(BOARD_TAG1) $(BOARD_TAG2) $(BOARD_TAG3) $(BOARD_TAG4) $(BOARD_TAG5) $(BOARD_TAG6) $(BOARD_TAG7) $(BOARD_TAG8) $(BOARD_TAG9) $(BOARD_TAG10)
BOARD_OPTION_TAGS_LIST = $(BOARD_TAG1) $(BOARD_TAG2) $(BOARD_TAG3) $(BOARD_TAG4) $(BOARD_TAG5) $(BOARD_TAG6) $(BOARD_TAG7) $(BOARD_TAG8) $(BOARD_TAG9) $(BOARD_TAG10)

# STM32duino specifics
# ----------------------------------
#
APPLICATION_PATH := $(STM32DUINO_PATH)
PLATFORM_VERSION := STM32duino $(STM32DUINO_RELEASE) for Arduino $(ARDUINO_IDE_RELEASE)

HARDWARE_PATH = $(APPLICATION_PATH)/hardware/stm32/$(STM32DUINO_RELEASE)
TOOL_CHAIN_PATH = $(APPLICATION_PATH)/tools/xpack-arm-none-eabi-gcc/$(STM32DUINO_GCC_ARM_RELEASE)
OTHER_TOOLS_PATH = $(APPLICATION_PATH)/tools/STM32Tools/$(STM32DUINO_TOOLS_RELEASE)
OPENOCD_PATH = $(APPLICATION_PATH)/tools/xpack-openocd/$(STM32DUINO_OPENOCD_RELEASE)

ifeq ($(OPERATING_SYSTEM),Darwin)
    STM32_TOOLS_BIN = $(OTHER_TOOLS_PATH)/macosx
else
    STM32_TOOLS_BIN = $(OTHER_TOOLS_PATH)/linux
endif

APP_TOOLS_PATH := $(TOOL_CHAIN_PATH)/bin
APP_LIB_PATH := $(HARDWARE_PATH)/libraries
BOARDS_TXT := $(HARDWARE_PATH)/boards.txt

CMSIS_PATH = $(STM32DUINO_INITIAL)/tools/CMSIS/$(STM32DUINO_CMSIS_RELEASE)
CMSIS_DSP_PATH = $(STM32DUINO_INITIAL)/tools/CMSIS_DSP/$(STM32DUINO_CMSIS_DSP_RELEASE)
CMSIS_NN_PATH = $(STM32DUINO_INITIAL)/tools/CMSIS_NN/$(STM32DUINO_CMSIS_NN_RELEASE)

PLATFORM := STM32duino
SUB_PLATFORM = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.core)

BUILD_CORE = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.core)
BUILD_BOARD = $(call SEARCH_FOR,$(BOARD_OPTION_TAGS_LIST),build.board)
ifeq ($(BUILD_BOARD),)
    BUILD_BOARD = $(call PARSE_BOARD,$(BOARD_TAG),build.board)
endif
BUILD_SERIES = $(call SEARCH_FOR,$(BOARD_OPTION_TAGS_LIST),build.series)
ifeq ($(BUILD_SERIES),)
    BUILD_SERIES = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.series)
endif
BUILD_FAMILY = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.family)
ifeq ($(BUILD_FAMILY),)
    BUILD_FAMILY = GENERIC
endif
BUILD_PRODUCT_LINE = $(call SEARCH_FOR,$(BOARD_OPTION_TAGS_LIST),build.product_line)
ifeq ($(BUILD_PRODUCT_LINE),)
    BUILD_PRODUCT_LINE = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.product_line)
endif
BUILD_ARCH = STM32

# platform.txt build.info.flags
PLATFORM_TAG = EMCODE=$(RELEASE_NOW) ARDUINO=$(RELEASE_ARDUINO) STM32DUINO
PLATFORM_TAG += ARDUINO_$(BUILD_FAMILY) ARDUINO_$(BUILD_BOARD) ARDUINO_ARCH_$(BUILD_ARCH)
PLATFORM_TAG += $(BUILD_SERIES) $(BUILD_PRODUCT_LINE)
PLATFORM_TAG += BOARD_NAME='"$(BUILD_BOARD)"'

# Generate main.cpp
# ----------------------------------
#
MAIN_LOCK = true

ifneq ($(strip $(KEEP_MAIN)),true)
    PATH_TO_MAIN_CPP = $(HARDWARE_PATH)/cores/arduino
    $(shell echo "// " > ./main.cpp)
    $(shell echo "// main.cpp generated by emCode" >> ./main.cpp)
    $(shell echo "// from $(PATH_TO_MAIN_CPP)" >> ./main.cpp)
    $(shell echo "// at $$(date +'%d %b %Y %T')" >> ./main.cpp)
    $(shell echo "// ----------------------------------" >> ./main.cpp)
    $(shell echo "// DO NOT EDIT THIS FILE." >> ./main.cpp)
    $(shell echo "// ----------------------------------" >> ./main.cpp)
    $(shell echo "#if defined(EMCODE)" >> ./main.cpp)
    $(shell echo " " >> ./main.cpp)
    $(shell cat $(PATH_TO_MAIN_CPP)/main.cpp >> ./main.cpp)
    $(shell echo " " >> ./main.cpp)
    $(shell echo " " >> ./main.cpp)
    $(shell echo "#include \"$(PROJECT_NAME_AS_IDENTIFIER).$(SKETCH_EXTENSION)\"" >> ./main.cpp)
    $(shell echo " " >> ./main.cpp)
    $(shell echo "#endif // EMCODE" >> ./main.cpp)
endif # KEEP_MAIN

# Uploader
#
ifeq ($(UPLOADER),stlink)
    UPLOADER_EXEC = $(STM32_CUBE_PATH)/bin/STM32_Programmer_CLI
    UPLOADER_OPTS = -c port=SWD mode=UR -q -d $(TARGET_HEX) -rst
    COMMAND_UPLOAD = $(UPLOADER_EXEC) $(UPLOADER_OPTS)

else ifeq ($(UPLOADER),cp_hex)
    TARGET_BIN_CP = $(TARGET_HEX)
    USED_VOLUME_PORT = $(strip $(BOARD_VOLUME))

else ifeq ($(UPLOADER),openocd)
    UPLOADER_EXEC = $(OPENOCD_PATH)/bin/openocd
    OPENOCD_INTERFACE = $(call SEARCH_FOR,$(BOARD_OPTION_TAGS_LIST),upload.protocol)
    ifeq ($(OPENOCD_INTERFACE),)
        OPENOCD_INTERFACE = stlink
    endif
    OPENOCD_TARGET = $(call SEARCH_FOR,$(BOARD_OPTION_TAGS_LIST),openocd.target)
    UPLOADER_OPTS = -d2 -s $(OPENOCD_PATH)/openocd/scripts
    UPLOADER_OPTS += -f interface/$(OPENOCD_INTERFACE).cfg
    UPLOADER_OPTS += -f target/$(OPENOCD_TARGET).cfg
    COMMAND_UPLOAD = $(UPLOADER_EXEC) $(UPLOADER_OPTS) -c "program $(TARGET_ELF) verify reset exit"

else ifeq ($(UPLOADER),massStorage)
    UPLOADER_EXEC = $(STM32_TOOLS_BIN)/massStorageCopy.sh
    COMMAND_UPLOAD = $(UPLOADER_EXEC) -I $(TARGET_BIN) -O $(USED_VOLUME_PORT)

endif # UPLOADER

# Tool-chain names
#
COMPILER_PREFIX = arm-none-eabi
COMPILER_LOCK = false

LDSCRIPT = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.ldscript)
ifeq ($(LDSCRIPT),)
    LDSCRIPT = ldscript.ld
endif
VARIANT = $(call SEARCH_FOR,$(BOARD_OPTION_TAGS_LIST),build.variant)
ifeq ($(VARIANT),)
    VARIANT = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.variant)
endif

# Multiple locations for core libraries
#
CORE_LIB_PATH := $(shell find $(HARDWARE_PATH)/cores/arduino -type d)
SYSTEM_LIB_PATH := $(HARDWARE_PATH)/system

CORE_C_SRCS = $(foreach dir,$(CORE_LIB_PATH),$(wildcard $(dir)/*.c))
CORE_CPP_SRCS = $(filter-out %main.cpp,$(foreach dir,$(CORE_LIB_PATH),$(wildcard $(dir)/*.cpp)))

CORE_AS1_SRCS = $(foreach dir,$(CORE_LIB_PATH),$(wildcard $(dir)/*.S))
CORE_AS2_SRCS = $(foreach dir,$(CORE_LIB_PATH),$(wildcard $(dir)/*.s))

CORE_AS1_SRCS_OBJ = $(patsubst %.S,%.S.o,$(filter %S, $(CORE_AS1_SRCS)))
CORE_AS2_SRCS_OBJ = $(patsubst %.s,%.s.o,$(filter %s, $(CORE_AS2_SRCS)))

# unused CORE_H_SRCS = $(foreach dir,$(CORE_LIB_PATH),$(wildcard $(dir)/*.h))

CORE_OBJ_FILES += $(CORE_C_SRCS:.c=.c.o) $(CORE_CPP_SRCS:.cpp=.cpp.o) $(CORE_AS1_SRCS_OBJ) $(CORE_AS2_SRCS_OBJ)
CORE_OBJS += $(patsubst $(HARDWARE_PATH)/%,$(OBJDIR)/%,$(CORE_OBJ_FILES))

CORE_LIBS_LOCK = 1

# SrcWrapper is required by recipe.hooks.prebuild and must be compiled
#
BUILD_CORE_LIB_PATH := $(shell find $(HARDWARE_PATH)/libraries/SrcWrapper -type d)

BUILD_CORE_C_SRCS = $(foreach dir,$(BUILD_CORE_LIB_PATH),$(wildcard $(dir)/*.c))
BUILD_CORE_CPP_SRCS = $(filter-out %main.cpp,$(foreach dir,$(BUILD_CORE_LIB_PATH),$(wildcard $(dir)/*.cpp)))

BUILD_CORE_AS1_SRCS = $(foreach dir,$(BUILD_CORE_LIB_PATH),$(wildcard $(dir)/*.S))
BUILD_CORE_AS2_SRCS = $(foreach dir,$(BUILD_CORE_LIB_PATH),$(wildcard $(dir)/*.s))

BUILD_CORE_AS1_SRCS_OBJ = $(patsubst %.S,%.S.o,$(filter %S, $(BUILD_CORE_AS1_SRCS)))
BUILD_CORE_AS2_SRCS_OBJ = $(patsubst %.s,%.s.o,$(filter %s, $(BUILD_CORE_AS2_SRCS)))

BUILD_CORE_OBJ_FILES += $(BUILD_CORE_C_SRCS:.c=.c.o) $(BUILD_CORE_CPP_SRCS:.cpp=.cpp.o) $(BUILD_CORE_AS1_SRCS_OBJ) $(BUILD_CORE_AS2_SRCS_OBJ)
BUILD_CORE_OBJS += $(patsubst $(HARDWARE_PATH)/%,$(OBJDIR)/%,$(BUILD_CORE_OBJ_FILES))

# Variant libraries — paths may contain parentheses
#
VARIANT_PATH = $(HARDWARE_PATH)/variants/$(VARIANT)

VARIANT_CPP_SRCS = $(shell find "$(VARIANT_PATH)" -maxdepth 1 -name '*.cpp' 2>/dev/null)
VARIANT_C_SRCS = $(shell find "$(VARIANT_PATH)" -maxdepth 1 -name '*.c' 2>/dev/null)

VARIANT_OBJ_FILES = $(VARIANT_CPP_SRCS:.cpp=.cpp.o) $(VARIANT_C_SRCS:.c=.c.o)
VARIANT_OBJS = $(patsubst $(HARDWARE_PATH)/%,$(OBJDIR)/%,$(VARIANT_OBJ_FILES))

F_CPU = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.f_cpu)
MCU = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.mcu)
ifeq ($(MCU),)
    MCU = cortex-m3
endif
MCU_FLAG_NAME = mcpu

# compiler.stm.extra_include from platform.txt
INCLUDE_PATH += $(CURRENT_DIR)
INCLUDE_PATH += $(HARDWARE_PATH)/cores/arduino/avr
INCLUDE_PATH += $(HARDWARE_PATH)/cores/arduino/stm32
INCLUDE_PATH += $(HARDWARE_PATH)/cores/arduino/api/deprecated
INCLUDE_PATH += $(HARDWARE_PATH)/libraries/SrcWrapper/inc
INCLUDE_PATH += $(HARDWARE_PATH)/libraries/SrcWrapper/inc/LL
INCLUDE_PATH += $(SYSTEM_LIB_PATH)/Drivers/$(BUILD_SERIES)_HAL_Driver/Inc
INCLUDE_PATH += $(SYSTEM_LIB_PATH)/Drivers/$(BUILD_SERIES)_HAL_Driver/Src
INCLUDE_PATH += $(SYSTEM_LIB_PATH)/$(BUILD_SERIES)
INCLUDE_PATH += $(HARDWARE_PATH)/libraries/USBDevice/inc
INCLUDE_PATH += $(SYSTEM_LIB_PATH)/Middlewares/ST/STM32_USB_Device_Library/Core/Inc
INCLUDE_PATH += $(SYSTEM_LIB_PATH)/Middlewares/ST/STM32_USB_Device_Library/Core/Src
INCLUDE_PATH += $(HARDWARE_PATH)/libraries/VirtIO/inc
INCLUDE_PATH += $(SYSTEM_LIB_PATH)/Middlewares/OpenAMP
INCLUDE_PATH += $(SYSTEM_LIB_PATH)/Middlewares/OpenAMP/open-amp/lib/include
INCLUDE_PATH += $(SYSTEM_LIB_PATH)/Middlewares/OpenAMP/libmetal/lib/include
INCLUDE_PATH += $(SYSTEM_LIB_PATH)/Middlewares/OpenAMP/virtual_driver

# compiler.arm.cmsis.c.flags from platform.txt
INCLUDE_PATH += $(CMSIS_PATH)/CMSIS/Core/Include
INCLUDE_PATH += $(SYSTEM_LIB_PATH)/Drivers/CMSIS/Device/ST/$(BUILD_SERIES)/Include
INCLUDE_PATH += $(SYSTEM_LIB_PATH)/Drivers/CMSIS/Device/ST/$(BUILD_SERIES)/Source
INCLUDE_PATH += $(SYSTEM_LIB_PATH)/Drivers/CMSIS/Device/ST/$(BUILD_SERIES)/Source/Templates/gcc
INCLUDE_PATH += $(CMSIS_DSP_PATH)/Include
INCLUDE_PATH += $(CMSIS_DSP_PATH)/PrivateInclude
INCLUDE_PATH += $(HARDWARE_PATH)/cores/arduino

FLAGS_FPU = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.flags.fp)
FLAGS_FPU += $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.fpu)
FLAGS_FPU += $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.float-abi)

# Protect strange paths
INCLUDE_PATH := $(patsubst %,"%",$(INCLUDE_PATH))

WORK_4a = $(call SEARCH_FOR,$(BOARD_OPTION_TAGS_LIST),build.variant_h)
ifeq ($(WORK_4a),)
    WORK_4a = $(call PARSE_BOARD,$(BOARD_TAG),build.variant_h)
endif
WORK_4b = $(shell echo $(WORK_4a) | sed 's:{build.board}:$(BUILD_BOARD):')
ifeq ($(WORK_4b),)
    WORK_4b = variant_generic.h
endif
FLAGS_D += VARIANT_H='"$(WORK_4b)"'

FLASH_OFFSET = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.flash_offset)
ifeq ($(FLASH_OFFSET),)
    FLASH_OFFSET = 0x0
endif
MAX_FLASH_SIZE = $(call SEARCH_FOR,$(BOARD_OPTION_TAGS_LIST),upload.maximum_size)
ifeq ($(MAX_FLASH_SIZE),)
    MAX_FLASH_SIZE = $(call PARSE_BOARD,$(BOARD_TAG),upload.maximum_size)
endif
MAX_RAM_SIZE = $(call SEARCH_FOR,$(BOARD_OPTION_TAGS_LIST),upload.maximum_data_size)
ifeq ($(MAX_RAM_SIZE),)
    MAX_RAM_SIZE = $(call PARSE_BOARD,$(BOARD_TAG),upload.maximum_data_size)
endif

# $(info *** MAX_FLASH_SIZE '$(MAX_FLASH_SIZE)')
# $(info *** MAX_RAM_SIZE '$(MAX_RAM_SIZE)')

# platform.txt build.usb_flags=-DUSBCON {build.usb_speed} -DUSBD_VID={build.vid} -DUSBD_PID={build.pid} -DHAL_PCD_MODULE_ENABLED
WORK_0a = $(call PARSE_FILE,build,usb_flags=,$(HARDWARE_PATH)/platform.txt)

# boards.txt for build.usb_speed build.vid build.pid
BUILD_USB_SPEED = $(call SEARCH_FOR,$(BOARD_OPTION_TAGS_LIST),build.usb_speed)
BUILD_VID = $(call SEARCH_FOR,$(BOARD_OPTION_TAGS_LIST),build.vid)
ifeq ($(BUILD_VID),)
    BUILD_VID = $(call PARSE_BOARD,$(BOARD_TAG),vid.0)
endif
ifeq ($(BUILD_VID),)
    BUILD_VID = 0x0483
endif
BUILD_PID = $(call SEARCH_FOR,$(BOARD_OPTION_TAGS_LIST),build.pid)
ifeq ($(BUILD_PID),)
    BUILD_PID = $(call PARSE_BOARD,$(BOARD_TAG),pid.0)
endif
ifeq ($(BUILD_PID),)
    BUILD_PID = 0x5740
endif

WORK_0b = $(shell echo '$(WORK_0a)' | sed 's:{build.usb_speed}:$(BUILD_USB_SPEED):g')
WORK_0c = $(shell echo '$(WORK_0b)' | sed 's:{build.vid}:$(BUILD_VID):g')
WORK_0d = $(shell echo '$(WORK_0c)' | sed 's:{build.pid}:$(BUILD_PID):g')

BUILD_USB_FLAGS = $(WORK_0d)

# boards.txt build.enable_usb={build.usb_flags} -DUSBD_USE_CDC
WORK_2a = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.enable_usb)
WORK_2b = $(shell echo '$(WORK_2a)' | sed 's:{build.usb_flags}:$(BUILD_USB_FLAGS):g')
BUILD_ENABLE_USB = $(WORK_2b)

# platform.txt / boards.txt build.st_extra_flags=-D{build.product_line} {build.enable_usb} {build.xSerial}
WORK_1a = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.st_extra_flags)

# boards.txt for build.bootloader_flags build.enable_virtio build.product_line build.xSerial
BUILD_BOOTLOADER_FLAGS = $(call SEARCH_FOR,$(BOARD_OPTION_TAGS_LIST),build.bootloader_flags)
BUILD_ENABLE_VIRTIO = $(call SEARCH_FOR,$(BOARD_OPTION_TAGS_LIST),build.enable_virtio)

BUILD_XSERIAL = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.xSerial)
ifeq ($(BUILD_XSERIAL),)
    BUILD_XSERIAL := -DHAL_UART_MODULE_ENABLED
endif

WORK_1b = $(shell echo '$(WORK_1a)' | sed 's:{build.bootloader_flags}:$(BUILD_BOOTLOADER_FLAGS):g')
WORK_1c = $(shell echo '$(WORK_1b)' | sed 's:{build.enable_virtio}:$(BUILD_ENABLE_VIRTIO):g')
WORK_1d = $(shell echo '$(WORK_1c)' | sed 's:{build.product_line}:$(BUILD_PRODUCT_LINE):g')
WORK_1e = $(shell echo '$(WORK_1d)' | sed 's:{build.xSerial}:$(BUILD_XSERIAL):g')
WORK_1f = $(shell echo '$(WORK_1e)' | sed 's:{build.enable_usb}:$(BUILD_ENABLE_USB):g')

BUILD_ST_EXTRA_FLAGS = $(WORK_1f)

BUILD_EXTRA_FLAGS = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.extra_flags)
BUILD_PERIPHERAL_PINS = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.peripheral_pins)
BUILD_STARTUP_FILE = $(call SEARCH_FOR,$(BOARD_TAGS_LIST),build.startup_file)

BUILD_LDSPECS = $(call SEARCH_FOR,$(BOARD_OPTION_TAGS_LIST),build.flags.ldspecs)
ifeq ($(BUILD_LDSPECS),)
    BUILD_LDSPECS = --specs=nano.specs
endif

# recipe.hooks.prebuild.1.pattern
COMMAND_BEFORE_COMPILE = sh $(SYSTEM_LIB_PATH)/extras/prebuild.sh $(BUILDS_PATH) $(CURRENT_DIR) $(HARDWARE_PATH) usb=$(BUILD_ENABLE_USB) virtio=$(BUILD_ENABLE_VIRTIO)

MESSAGE_BEFORE = "Set build options"

# Flags for gcc, g++ and linker
# ----------------------------------
#
# compiler.extra_flags=-mcpu={build.mcu} {build.fpu} {build.float-abi} -DVECT_TAB_OFFSET={build.flash_offset} {build.hal} -DEXTENDED_PIN_MODE -mthumb "@{build.opt.path}"
#
FLAGS_ALL = $(OPTIMISATION) $(FLAGS_WARNING)
FLAGS_ALL += -$(MCU_FLAG_NAME)=$(MCU)
ifneq ($(F_CPU),)
    FLAGS_ALL += -DF_CPU=$(F_CPU)
endif
FLAGS_ALL += $(FLAGS_FPU)
FLAGS_ALL += -DVECT_TAB_OFFSET=$(FLASH_OFFSET)
FLAGS_ALL += -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER
FLAGS_ALL += -DEXTENDED_PIN_MODE -mthumb
FLAGS_ALL += -ffunction-sections -fdata-sections
FLAGS_ALL += --param max-inline-insns-single=500 -MMD
FLAGS_ALL += $(addprefix -D, $(PLATFORM_TAG) $(FLAGS_D))
FLAGS_ALL += @$(BUILDS_PATH)/sketch/build.opt
FLAGS_ALL += $(addprefix -I, $(INCLUDE_PATH)) -I"$(VARIANT_PATH)"
FLAGS_ALL += $(BUILD_ST_EXTRA_FLAGS)
FLAGS_ALL += $(BUILD_EXTRA_FLAGS)

# Specific FLAGS_C for gcc only
# gcc uses FLAGS_ALL and FLAGS_C
# compiler.c.st_extra_flags={build.peripheral_pins}
#
FLAGS_C = -std=gnu17 $(BUILD_PERIPHERAL_PINS)

# Specific FLAGS_CPP for g++ only
# g++ uses FLAGS_ALL and FLAGS_CPP
#
FLAGS_CPP = -fno-threadsafe-statics -fno-rtti -fno-exceptions -fno-use-cxa-atexit -std=gnu++17

# Specific FLAGS_AS for gcc assembler only
# gcc assembler uses FLAGS_ALL and FLAGS_AS
# compiler.S.st_extra_flags={build.startup_file}
#
FLAGS_AS = -x assembler-with-cpp $(BUILD_STARTUP_FILE)

# Specific FLAGS_LD for linker only
# linker uses FLAGS_ALL and FLAGS_LD
# compiler.c.elf.flags + compiler.ldflags
#
FLAGS_LD = $(OPTIMISATION) $(FLAGS_WARNING)
FLAGS_LD += -$(MCU_FLAG_NAME)=$(MCU) -mthumb
FLAGS_LD += $(FLAGS_FPU)
FLAGS_LD += -Wl,-Map,$(OBJDIR)/emCode.cpp.map
FLAGS_LD += -Wl,--default-script="$(VARIANT_PATH)/$(LDSCRIPT)"
FLAGS_LD += -Wl,--script="$(SYSTEM_LIB_PATH)/ldscript.ld"
FLAGS_LD += -Wl,--no-warn-rwx-segments
FLAGS_LD += -L$(BUILDS_PATH)
FLAGS_LD += $(addprefix -D, $(PLATFORM_TAG))
FLAGS_LD += $(BUILD_LDSPECS)
FLAGS_LD += -Wl,--defsym=LD_FLASH_OFFSET=$(FLASH_OFFSET)
FLAGS_LD += -Wl,--defsym=LD_MAX_SIZE=$(MAX_FLASH_SIZE)
FLAGS_LD += -Wl,--defsym=LD_MAX_DATA_SIZE=$(MAX_RAM_SIZE)
FLAGS_LD += -Wl,--cref -Wl,--check-sections -Wl,--gc-sections
FLAGS_LD += -Wl,--entry=Reset_Handler -Wl,--unresolved-symbols=report-all
FLAGS_LD += -Wl,--warn-common

INCLUDE_A = $(shell find "$(VARIANT_PATH)" -maxdepth 1 -name '*.a' 2>/dev/null)

# Specific FLAGS_OBJCOPY for objcopy only
# objcopy uses FLAGS_OBJCOPY only
#
FLAGS_OBJCOPY = -v -Oihex

# Target
#
TARGET_HEXBIN_1 = $(TARGET_HEX)
TARGET_HEXBIN_2 = $(TARGET_BIN)
COMMAND_COPY = $(OBJCOPY) -O binary $< $(TARGET_BIN)
COMMAND_POST_COPY = $(OBJCOPY) -O ihex $< $(TARGET_HEX)

# recipe.c.combine.pattern
COMMAND_LINK = $(CC) $(FLAGS_LD) $(OUT_PREPOSITION)$@ -Wl,--start-group $(FIRST_OBJS_IN_LINK) $(LOCAL_OBJS) $(LOCAL_ARCHIVES) $(USER_ARCHIVES) $(INCLUDE_A) $(TARGET_A) $(TARGET_CORE_A) -lc -Wl,--end-group -lm -lgcc -lstdc++

endif # BOARD_CHECK

endif # MAKEFILE_NAME

